services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: alpyroot
      MYSQL_DATABASE: alpydb
      MYSQL_USER: alpyuser
      MYSQL_PASSWORD: alpypass
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    container_name: apache_php
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
